Added general method unit tests
pysat/pysatMadrigal pull request #59
Opened 2021-11-05 14:45 UTC by aburrell

# Description
Partially addresses #3 by adding unit tests for many of the general methods and simple file loading.

# Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality or documentation)
- This change requires a documentation update

# How Has This Been Tested?

Running the new unit tests

## Test Configuration
* Operating system: OS X Mojave
* Version number: Python 3.9
* Any details about your local setup that are relevant: requires pysat develop branch.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have linted the files updated in this pull request
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release

2021-11-08 14:09 UTC, jklenzing commented
I should have caught that `prep_dir` was used elsewhere in the pysat pull.  Should have been deprecated there instead of just moved, which is why these tests are breaking.  We can either use this with the develop branch of pysat, or switch back to the old path here and add a pass-through with DeprecationWarning in pysat develop to maintain usage.

2021-11-08 16:56 UTC, aburrell commented
It doesn't look like that's why it's failing, though.  It looks like it's failing because the tests aren't being skipped like they should be.

2021-11-08 20:06 UTC, aburrell commented
@jklenzing it's passing now!

2021-11-08 21:57 UTC, jklenzing requested changes
`prep_dir` is only required if you're creating subdirectories within the temporary directory.  In the core code, this is done sometimes because a full instrument path is needed (though it's likely not consistently done this way).  Since we're using the main directory already created by `tempfile`, it's not needed here, which means that all the skip logic can be removed.  Verified this by commenting out line 175 and running locally.

2021-11-08 21:57 UTC, jklenzing commented on pysatMadrigal/tests/test_methods_general.py
> +                    reason="Test requires pysat 3.0.2+")
```suggestion
```

2021-11-08 21:57 UTC, jklenzing commented on pysatMadrigal/tests/test_methods_general.py
> +        testing.prep_dir(self.data_path.name)
```suggestion
```

2021-11-08 21:57 UTC, jklenzing commented on pysatMadrigal/tests/test_methods_general.py
> +from pysat.utils import testing
```suggestion
```

2021-11-08 21:57 UTC, jklenzing commented on pysatMadrigal/tests/test_methods_general.py
> +
```suggestion
```

2021-11-09 20:06 UTC, jklenzing approved these changes
Looks good! Minor comment on spelling.

2021-11-09 22:09 UTC, aburrell commented on pysatMadrigal/tests/test_methods_general.py
> +        """Tesst raises ValueError for unexpected date_array input."""
SSSSS 🐍

2021-11-09 22:10 UTC, merged